Update LIFXMultiZone.groovy
robheyes/lifxcode pull request #94
Opened 2020-10-26 21:09 UTC by ngaustad

Fixed issue where duration was not using seconds.

2020-10-26 21:13 UTC, ngaustad commented
The duration for multizone lights (I do not own any other lifx lights so I'm not sure if this issue exists there) was always happening instantly regardless of what I set the duration to, in testing if I set the duration to 5000 it would take 5 seconds, it looks like this bit of the code was not accounting for the millisecond conversion.

2020-10-27 01:11 UTC, dkilgore90 requested changes

2020-10-27 01:11 UTC, dkilgore90 commented on LIFXMultiZone.groovy
> +        setZones('999:"[brightness: ' + level + ']"', duration * 1000)
I think you actually want this change at line 120, in `setZones`, so that the conversion from s to ms occurs for all calls.

2020-10-27 02:23 UTC, ngaustad reviewed
Yes, my change worked for everything I was using it for but this is more complete.

2020-10-31 20:32 UTC, dkilgore90 approved these changes

2020-11-02 11:55 UTC, merged